CREATE TABLE IF NOT EXISTS gladiators (
    Name VARCHAR(255),
    Age INT,
    BirthYear INT,
    Origin VARCHAR(255),
    Height INT,
    Weight INT,
    Category VARCHAR(255),
    Wins INT,
    Losses INT,
    SpecialSkills VARCHAR(255),
    WeaponOfChoice VARCHAR(255),
    PatronWealth VARCHAR(255),
    EquipmentQuality VARCHAR(255),
    PublicFavor DECIMAL(10, 9),
    InjuryHistory VARCHAR(255),
    MentalResilience VARCHAR(255),
    DietAndNutrition VARCHAR(255),
    TacticalKnowledge VARCHAR(255),
    AllegianceNetwork VARCHAR(255),
    BattleExperience INT,
    PsychologicalProfile VARCHAR(255),
    HealthStatus VARCHAR(255),
    PersonalMotivation VARCHAR(255),
    PreviousOccupation VARCHAR(255),
    TrainingIntensity VARCHAR(255),
    BattleStrategy VARCHAR(255),
    SocialStanding VARCHAR(255),
    CrowdAppealTechniques VARCHAR(255),
    Survived VARCHAR(10)
);